"""VISA attribute availability from VPP-4.3 Revision 7.2.1.

This module is intentionally self-contained. ``VISA_RESOURCE_TYPES_BY_ATTRIBUTE``
maps each VISA attribute to every resource type for which it is possible.

You can use it to generate "attributes.py"
"""

VISA_RESOURCE_TYPES = (
	"RESOURCE_MANAGER",
	"INSTR:VXI",
	"INSTR:GPIB-VXI",
	"INSTR:GPIB",
	"INSTR:ASRL",
	"INSTR:TCPIP:VXI-11",
	"INSTR:TCPIP:HiSLIP",
	"INSTR:USB",
	"INSTR:PXI",
	"MEMACC:VXI",
	"MEMACC:GPIB-VXI",
	"MEMACC:PXI",
	"INTFC:GPIB",
	"BACKPLANE:VXI",
	"BACKPLANE:GPIB-VXI",
	"BACKPLANE:PXI",
	"SERVANT:VXI",
	"SERVANT:GPIB",
	"SERVANT:TCPIP",
	"SOCKET:TCPIP",
)

_RESOURCE_TYPE_GROUPS = {
	"INSTR": tuple(resource_type for resource_type in VISA_RESOURCE_TYPES if resource_type.startswith("INSTR:")),
	"MEMACC": tuple(resource_type for resource_type in VISA_RESOURCE_TYPES if resource_type.startswith("MEMACC:")),
	"INTFC": ("INTFC:GPIB",),
	"BACKPLANE": tuple(resource_type for resource_type in VISA_RESOURCE_TYPES if resource_type.startswith("BACKPLANE:")),
	"SERVANT": tuple(resource_type for resource_type in VISA_RESOURCE_TYPES if resource_type.startswith("SERVANT:")),
	"SOCKET": ("SOCKET:TCPIP",),
}

_INSTR_MESSAGE_BASED = (
	"INSTR:GPIB", "INSTR:GPIB-VXI", "INSTR:VXI", "INSTR:ASRL", "INSTR:TCPIP:VXI-11",
	"INSTR:TCPIP:HiSLIP", "INSTR:USB",
)
_INSTR_GPIB = ("INSTR:GPIB", "INSTR:GPIB-VXI")
_INSTR_VXI = ("INSTR:VXI", "INSTR:GPIB-VXI")
_INSTR_TCPIP = ("INSTR:TCPIP:VXI-11", "INSTR:TCPIP:HiSLIP")

VISA_RESOURCE_TYPES_BY_ATTRIBUTE = {}


def _add(attributes, resource_types):
	for attribute in attributes:
		VISA_RESOURCE_TYPES_BY_ATTRIBUTE.setdefault(attribute, set()).update(resource_types)


# VISA Resource Template attributes are inherited by every resource type.
_add((
	"VI_ATTR_RSRC_NAME", "VI_ATTR_RSRC_SPEC_VERSION", "VI_ATTR_RSRC_IMPL_VERSION",
	"VI_ATTR_RSRC_MANF_ID", "VI_ATTR_RSRC_MANF_NAME", "VI_ATTR_RM_SESSION",
	"VI_ATTR_USER_DATA", "VI_ATTR_USER_DATA_32", "VI_ATTR_USER_DATA_64",
	"VI_ATTR_MAX_QUEUE_LENGTH", "VI_ATTR_RSRC_CLASS", "VI_ATTR_RSRC_LOCK_STATE",
), VISA_RESOURCE_TYPES)

_add((
	"VI_ATTR_INTF_NUM", "VI_ATTR_INTF_TYPE", "VI_ATTR_INTF_INST_NAME",
	"VI_ATTR_TMO_VALUE",
), VISA_RESOURCE_TYPES[1:])

_add(("VI_ATTR_TRIG_ID",), _RESOURCE_TYPE_GROUPS["INSTR"] + _RESOURCE_TYPE_GROUPS["BACKPLANE"])
_add(("VI_ATTR_DMA_ALLOW_EN",), _RESOURCE_TYPE_GROUPS["INSTR"] + _RESOURCE_TYPE_GROUPS["MEMACC"] + _RESOURCE_TYPE_GROUPS["INTFC"] + _RESOURCE_TYPE_GROUPS["SERVANT"] + _RESOURCE_TYPE_GROUPS["SOCKET"])

# Message-based INSTR attributes.
_add((
	"VI_ATTR_FILE_APPEND_EN", "VI_ATTR_IO_PROT", "VI_ATTR_RD_BUF_OPER_MODE",
	"VI_ATTR_RD_BUF_SIZE", "VI_ATTR_SEND_END_EN", "VI_ATTR_SUPPRESS_END_EN",
	"VI_ATTR_TERMCHAR", "VI_ATTR_TERMCHAR_EN", "VI_ATTR_WR_BUF_OPER_MODE",
	"VI_ATTR_WR_BUF_SIZE",
), _INSTR_MESSAGE_BASED)

_add((
	"VI_ATTR_GPIB_PRIMARY_ADDR", "VI_ATTR_GPIB_SECONDARY_ADDR",
	"VI_ATTR_GPIB_READDR_EN", "VI_ATTR_GPIB_UNADDR_EN", "VI_ATTR_GPIB_REN_STATE",
), _INSTR_GPIB)

_add((
	"VI_ATTR_MAINFRAME_LA", "VI_ATTR_MEM_BASE", "VI_ATTR_MEM_BASE_32",
	"VI_ATTR_MEM_BASE_64", "VI_ATTR_MEM_SIZE", "VI_ATTR_MEM_SIZE_32",
	"VI_ATTR_MEM_SIZE_64", "VI_ATTR_MEM_SPACE", "VI_ATTR_VXI_LA",
	"VI_ATTR_CMDR_LA", "VI_ATTR_IMMEDIATE_SERV", "VI_ATTR_FDC_CHNL",
	"VI_ATTR_FDC_GEN_SIGNAL_EN", "VI_ATTR_FDC_MODE", "VI_ATTR_FDC_USE_PAIR",
	"VI_ATTR_SRC_BYTE_ORDER", "VI_ATTR_DEST_BYTE_ORDER", "VI_ATTR_WIN_BYTE_ORDER",
	"VI_ATTR_SRC_ACCESS_PRIV", "VI_ATTR_DEST_ACCESS_PRIV", "VI_ATTR_WIN_ACCESS_PRIV",
	"VI_ATTR_VXI_DEV_CLASS", "VI_ATTR_VXI_TRIG_SUPPORT",
), _INSTR_VXI)

_add(("VI_ATTR_INTF_PARENT_NUM",), ("INSTR:GPIB-VXI",))

_add((
	"VI_ATTR_ASRL_AVAIL_NUM", "VI_ATTR_ASRL_BAUD", "VI_ATTR_ASRL_DATA_BITS",
	"VI_ATTR_ASRL_PARITY", "VI_ATTR_ASRL_STOP_BITS", "VI_ATTR_ASRL_FLOW_CNTRL",
	"VI_ATTR_ASRL_END_IN", "VI_ATTR_ASRL_END_OUT", "VI_ATTR_ASRL_CTS_STATE",
	"VI_ATTR_ASRL_DCD_STATE", "VI_ATTR_ASRL_DSR_STATE", "VI_ATTR_ASRL_DTR_STATE",
	"VI_ATTR_ASRL_RI_STATE", "VI_ATTR_ASRL_RTS_STATE", "VI_ATTR_ASRL_REPLACE_CHAR",
	"VI_ATTR_ASRL_XON_CHAR", "VI_ATTR_ASRL_XOFF_CHAR",
), ("INSTR:ASRL",))

_add((
	"VI_ATTR_TCPIP_ADDR", "VI_ATTR_TCPIP_HOSTNAME", "VI_ATTR_TCPIP_DEVICE_NAME",
	"VI_ATTR_TCPIP_IS_HISLIP",
), _INSTR_TCPIP)

_add((
	"VI_ATTR_TCPIP_SERVER_CERT", "VI_ATTR_TCPIP_SERVER_CERT_SIZE",
	"VI_ATTR_TCPIP_SERVER_CERT_ISSUER_NAME", "VI_ATTR_TCPIP_SERVER_CERT_SUBJECT_NAME",
	"VI_ATTR_TCPIP_SERVER_CERT_EXPIRATION_DATE", "VI_ATTR_TCPIP_SASL_MECHANISM",
	"VI_ATTR_TCPIP_TLS_CIPHER_SUITE", "VI_ATTR_TCPIP_SERVER_CERT_IS_PERPETUAL",
), ("INSTR:TCPIP:HiSLIP",))

_add((
	"VI_ATTR_TCPIP_HISLIP_OVERLAP_EN", "VI_ATTR_TCPIP_HISLIP_VERSION",
	"VI_ATTR_TCPIP_HISLIP_MAX_MESSAGE_KB", "VI_ATTR_TCPIP_HISLIP_ENCRYPTION_EN",
), ("INSTR:TCPIP:HiSLIP",))

_add(("VI_ATTR_4882_COMPLIANT",), ("INSTR:VXI", "INSTR:GPIB-VXI", "INSTR:USB"))
_add(("VI_ATTR_MANF_ID", "VI_ATTR_MODEL_CODE", "VI_ATTR_MANF_NAME", "VI_ATTR_MODEL_NAME"), ("INSTR:VXI", "INSTR:GPIB-VXI", "INSTR:USB", "INSTR:PXI"))
_add((
	"VI_ATTR_USB_SERIAL_NUM", "VI_ATTR_USB_INTFC_NUM", "VI_ATTR_USB_MAX_INTR_SIZE",
	"VI_ATTR_USB_PROTOCOL",
), ("INSTR:USB",))
_add((
	"VI_ATTR_SLOT", "VI_ATTR_SRC_INCREMENT", "VI_ATTR_DEST_INCREMENT",
	"VI_ATTR_WIN_ACCESS", "VI_ATTR_WIN_BASE_ADDR", "VI_ATTR_WIN_BASE_ADDR_32",
	"VI_ATTR_WIN_BASE_ADDR_64", "VI_ATTR_WIN_SIZE", "VI_ATTR_WIN_SIZE_32",
	"VI_ATTR_WIN_SIZE_64",
), _INSTR_VXI + ("INSTR:PXI",))

for _attribute_kind in ("TYPE", "BASE", "SIZE"):
	for _bar in range(6):
		if _attribute_kind != "SIZE":
			_add((f"VI_ATTR_PXI_MEM_{_attribute_kind}_BAR{_bar}",), ("INSTR:PXI",))
		if _attribute_kind in ("BASE", "SIZE"):
			_add((
				f"VI_ATTR_PXI_MEM_{_attribute_kind}_BAR{_bar}_32",
				f"VI_ATTR_PXI_MEM_{_attribute_kind}_BAR{_bar}_64",
			), ("INSTR:PXI",))

_add((
	"VI_ATTR_PXI_BUS_NUM", "VI_ATTR_PXI_DEV_NUM", "VI_ATTR_PXI_FUNC_NUM",
	"VI_ATTR_PXI_SLOTPATH", "VI_ATTR_PXI_SLOT_LBUS_LEFT", "VI_ATTR_PXI_SLOT_LBUS_RIGHT",
	"VI_ATTR_PXI_TRIG_BUS", "VI_ATTR_PXI_STAR_TRIG_BUS", "VI_ATTR_PXI_STAR_TRIG_LINE",
	"VI_ATTR_PXI_CHASSIS", "VI_ATTR_PXI_IS_EXPRESS", "VI_ATTR_PXI_SLOT_LWIDTH",
	"VI_ATTR_PXI_MAX_LWIDTH", "VI_ATTR_PXI_ACTUAL_LWIDTH", "VI_ATTR_PXI_DSTAR_BUS",
	"VI_ATTR_PXI_DSTAR_SET", "VI_ATTR_PXI_ALLOW_WRITE_COMBINE",
	"VI_ATTR_PXI_SLOT_WIDTH", "VI_ATTR_PXI_SLOT_OFFSET",
), ("INSTR:PXI",))

# MEMACC-specific tables.
_add((
	"VI_ATTR_SRC_INCREMENT", "VI_ATTR_DEST_INCREMENT", "VI_ATTR_WIN_ACCESS",
	"VI_ATTR_WIN_BASE_ADDR", "VI_ATTR_WIN_BASE_ADDR_32", "VI_ATTR_WIN_BASE_ADDR_64",
	"VI_ATTR_WIN_SIZE", "VI_ATTR_WIN_SIZE_32", "VI_ATTR_WIN_SIZE_64",
	), ("MEMACC:VXI", "MEMACC:GPIB-VXI", "MEMACC:PXI"))

_add((
	"VI_ATTR_VXI_LA", "VI_ATTR_SRC_BYTE_ORDER", "VI_ATTR_DEST_BYTE_ORDER",
	"VI_ATTR_WIN_BYTE_ORDER", "VI_ATTR_SRC_ACCESS_PRIV", "VI_ATTR_DEST_ACCESS_PRIV",
	"VI_ATTR_WIN_ACCESS_PRIV",
), ("MEMACC:VXI", "MEMACC:GPIB-VXI"))

_add((
	"VI_ATTR_INTF_PARENT_NUM", "VI_ATTR_GPIB_PRIMARY_ADDR",
	"VI_ATTR_GPIB_SECONDARY_ADDR",
), ("MEMACC:GPIB-VXI",))

# INTFC-specific tables.
_add((
	"VI_ATTR_SEND_END_EN", "VI_ATTR_TERMCHAR", "VI_ATTR_TERMCHAR_EN",
	"VI_ATTR_DEV_STATUS_BYTE", "VI_ATTR_WR_BUF_OPER_MODE", "VI_ATTR_RD_BUF_OPER_MODE",
	"VI_ATTR_FILE_APPEND_EN", "VI_ATTR_RD_BUF_SIZE", "VI_ATTR_WR_BUF_SIZE",
	"VI_ATTR_GPIB_PRIMARY_ADDR", "VI_ATTR_GPIB_SECONDARY_ADDR", "VI_ATTR_GPIB_REN_STATE",
	"VI_ATTR_GPIB_ATN_STATE", "VI_ATTR_GPIB_NDAC_STATE", "VI_ATTR_GPIB_SRQ_STATE",
	"VI_ATTR_GPIB_CIC_STATE", "VI_ATTR_GPIB_SYS_CNTRL_STATE",
	"VI_ATTR_GPIB_HS488_CBL_LEN", "VI_ATTR_GPIB_ADDR_STATE",
), ("INTFC:GPIB",))

# BACKPLANE-specific tables.
_add((
	"VI_ATTR_MAINFRAME_LA", "VI_ATTR_VXI_VME_SYSFAIL_STATE",
	"VI_ATTR_VXI_VME_INTR_STATUS", "VI_ATTR_VXI_TRIG_STATUS", "VI_ATTR_VXI_TRIG_SUPPORT",
	), ("BACKPLANE:VXI", "BACKPLANE:GPIB-VXI"))

_add((
	"VI_ATTR_MANF_NAME", "VI_ATTR_MODEL_NAME", "VI_ATTR_PXI_CHASSIS",
	"VI_ATTR_PXI_TRIG_BUS", "VI_ATTR_PXI_SRC_TRIG_BUS", "VI_ATTR_PXI_DEST_TRIG_BUS",
), ("BACKPLANE:PXI",))

# SERVANT-specific tables.
_add((
	"VI_ATTR_SEND_END_EN", "VI_ATTR_TERMCHAR", "VI_ATTR_TERMCHAR_EN",
	"VI_ATTR_DEV_STATUS_BYTE", "VI_ATTR_WR_BUF_OPER_MODE", "VI_ATTR_RD_BUF_OPER_MODE",
	"VI_ATTR_FILE_APPEND_EN", "VI_ATTR_RD_BUF_SIZE", "VI_ATTR_WR_BUF_SIZE",
	), ("SERVANT:VXI", "SERVANT:GPIB", "SERVANT:TCPIP"))

_add((
	"VI_ATTR_GPIB_PRIMARY_ADDR", "VI_ATTR_GPIB_SECONDARY_ADDR", "VI_ATTR_GPIB_REN_STATE",
	"VI_ATTR_GPIB_ADDR_STATE",
), ("SERVANT:GPIB",))

_add(("VI_ATTR_VXI_LA", "VI_ATTR_CMDR_LA"), ("SERVANT:VXI",))
_add(("VI_ATTR_TCPIP_DEVICE_NAME",), ("SERVANT:TCPIP",))

# SOCKET-specific tables.
_add((
	"VI_ATTR_SEND_END_EN", "VI_ATTR_TERMCHAR", "VI_ATTR_TERMCHAR_EN",
	"VI_ATTR_WR_BUF_OPER_MODE", "VI_ATTR_RD_BUF_OPER_MODE", "VI_ATTR_FILE_APPEND_EN",
	"VI_ATTR_IO_PROT", "VI_ATTR_RD_BUF_SIZE", "VI_ATTR_WR_BUF_SIZE",
	"VI_ATTR_TCPIP_ADDR", "VI_ATTR_TCPIP_HOSTNAME", "VI_ATTR_TCPIP_PORT",
	"VI_ATTR_TCPIP_NODELAY", "VI_ATTR_TCPIP_KEEPALIVE", "VI_ATTR_TCPIP_SERVER_CERT",
	"VI_ATTR_TCPIP_SERVER_CERT_SIZE", "VI_ATTR_TCPIP_SERVER_CERT_ISSUER_NAME",
	"VI_ATTR_TCPIP_SERVER_CERT_SUBJECT_NAME", "VI_ATTR_TCPIP_SERVER_CERT_EXPIRATION_DATE",
	"VI_ATTR_TCPIP_TLS_CIPHER_SUITE", "VI_ATTR_TCPIP_SERVER_CERT_IS_PERPETUAL",
), ("SOCKET:TCPIP",))

VISA_RESOURCE_TYPES_BY_ATTRIBUTE = {
	attribute: tuple(sorted(resource_types))
	for attribute, resource_types in sorted(VISA_RESOURCE_TYPES_BY_ATTRIBUTE.items())
}

del _attribute_kind
del _bar


if __name__ == "__main__":
	from pprint import pprint

	print("VISA_RESOURCE_TYPES_BY_ATTRIBUTE = ", end="")
	pprint(VISA_RESOURCE_TYPES_BY_ATTRIBUTE, sort_dicts=False)